version: '3'

services: 
    nginx:
        image: nginx:latest
        volumes:
            - ./frontside/:/var/www/frontside/dist/
            - ./backend/:/var/www/backend/dist/
           # - default.conf:/etc/nginx/conf.d/
        ports: 
            - 80:80
    chatDatabase:
        image: mysql:5.7
        restart: always
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
        environment: 
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: dev
            MYSQL_ROOT_PASSWORD: test
        expose:      
            - "3306"
        ports:
            - 3336:3336
        volumes: 
            - ./mysql:/var/lib/mysql
            - ./dump:/docker-entrypoint-initdb.d
    backend:
        build:
            context: .
            dockerfile: ./docker/DockerNode
        depends_on:
            - chatDatabase
        volumes: 
            - ./backend:/chatBackend
        restart: unless-stopped
        #env_file: ./.env
        ports:
        - 8000:8000
        # environment:
        #   - DB_HOST=mysqldb
        #   - DB_USER=$MYSQLDB_USER
        #   - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        #   - DB_NAME=$MYSQLDB_DATABASE
        #   - DB_PORT=$MYSQLDB_DOCKER_PORT
        stdin_open: true
        tty: true
